version: "3"

services: 
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    volumes:
      - .:/backend
    restart: on-failure
  frontend:
    build:
      context: 
        ./frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
    restart: on-failure
    ports: 
      - "8080:8080"
